version: '3.7'
networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        ipam:
            driver: default
            config: [{subnet: 192.168.7.0/24}]
services:
#Database
  database:
    image: mysql:5.7
    container_name: db
    # ports:
      # - "3306:3306"
    env_file:
      - env/database.env
#DNS Server
  authoritative:
    build: .
    image: powerdns:latest
    container_name: powerdns
    links:
      - database:db
    # ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"
    entrypoint: /start.sh
    env_file:
      - env/database.env
#DNS Admin
  pdnsadmin:
    image: pdnsadmin/pdnsadmin:latest
    container_name: pdnsadmin
    hostname: pdnsadmin
    links:
      - database:db
      - authoritative:powerdns
    ports:
      - "${PDA_PORT}:80"
    env_file:
      - env/database.env
    labels:
      traefik.enable: 'true'
      traefik.backend: pdnsadmin
      traefik.protocol: http
      traefik.port: 80
      traefik.frontend.rule: 'Host:pdnsadmin.${DOMAINNAME}'
      traefik.frontend.headers.SSLHost: 'pdnsadmin.${DOMAINNAME}'
      traefik.docker.network: traefik_proxy
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.headers.SSLForceHost: 'true'
      traefik.frontend.headers.SSLRedirect: 'true'
      traefik.frontend.headers.browserXSSFilter: 'true'
      traefik.frontend.headers.contentTypeNosniff: 'true'
      traefik.frontend.headers.forceSTSHeader: 'true'
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: 'true'
      traefik.frontend.headers.STSPreload: 'true'
      traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
      traefik.frontend.headers.frameDeny: 'true'
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
    networks:
      - default
      - traefik_proxy      
