version: '3.1'
services:
 # CoreDNS - simple DNS service
    coredns:
        build: .
        container_name: coredns
        restart: always
        expose:
            - '53'
            - 53/udp
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - '/home/fabrice/docker/coredns/config:/etc/coredns'
        labels:
            com.centurylinklabs.watchtower.enable: 'false'
