
version: "3.7"


networks:

  traefik_proxy:

    external:

      name: traefik_proxy

  default:

#    driver: bridge

    ipam:

      driver: default

      config:

         - subnet: 192.168.3.0/24

#           ip_range: 192.168.5.0/24

#           gateway: 192.168.5.1

services:

# Firefox - Web Broswer

  firefox:

    image: jlesage/firefox

    container_name: firefox

    hostname: firefox 

    restart: unless-stopped

    networks: 

      - traefik_proxy

    ports: 

      - "${FIREFOX_PORT}:5800"

    volumes:

      - ${USERDIR}/docker/firefox/config:/config

      - ${USERDIR}/docker/firefox/downloads:/config/downloads

      - /dev/shm:/dev/shm

      - ${USERDIR}/docker/firefox/shared:/shared

    environment:

      USER_ID: ${PUID}

      GROUP_ID: ${PGID}

      TZ: ${TZ}

      UMASK: 002

      KEEP_APP_RUNNING: 1

      CLEAN_TMP_DIR: 1

      DISPLAY_WIDTH: 1600

      DISPLAY_HEIGHT: 960

      VNC_PASSWD: ${DEF_PASSWORD}

    labels:

      traefik.enable: "true"

      traefik.backend: firefox

      traefik.protocol: http

      traefik.port: 5800

      traefik.frontend.rule: Host:firefox.${DOMAINNAME}

      traefik.frontend.headers.SSLHost: firefox.${DOMAINNAME}

      traefik.docker.network: traefik_proxy

      traefik.frontend.passHostHeader: "true"

      traefik.frontend.headers.SSLForceHost: "true"

      traefik.frontend.headers.SSLRedirect: "true"

      traefik.frontend.headers.browserXSSFilter: "true"

      traefik.frontend.headers.contentTypeNosniff: "true"

      traefik.frontend.headers.forceSTSHeader: "true"

      traefik.frontend.headers.STSSeconds: 315360000

      traefik.frontend.headers.STSIncludeSubdomains: "true"

      traefik.frontend.headers.STSPreload: "true"

      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex

#      traefik.frontend.headers.frameDeny: "true" #customFrameOptionsValue overrides this

      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'

      traefik.frontend.auth.forward.address: "http://oauth:4181"

      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User

      traefik.frontend.auth.forward.trustForwardHeader: "true"
