
#------------------ My typical setup -------------------#
version: '2.3'
networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        ipam:
            driver: default
            config: [{subnet: 192.168.7.0/24}]
services:
#----------------------- Variables ---------------------#
# nginx 
# <service port>                                          # add this to the environment first
# <service's virtual port>                                # this is what the service "thinks" it is uses
# <service config directory>                              # normally within "${USERDIR}/docker/"
# <additional volumes, depending on the service>          # add more places, if needed
# <any additional parameters>    

#----------------------- Template ----------------------#

    fabricesemti.com :
        image: linuxserver/nginx                    #depends on the name of the image
        container_name: fabricesemti.com
        hostname: fabricesemti.com nginx 
        restart: unless-stopped
        networks:
            - traefik_proxy
        ports:
            - '${NGINX_PORT0}:80'
        volumes:
            - '${NGINX_HOME}/fabricesemti.com/config:/config'
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        labels:
            traefik.enable: 'true'
            traefik.backend: fabricesemti.com
            traefik.protocol: http
            traefik.port: 80
            traefik.frontend.rule: 'Host:${DOMAINNAME},www.${DOMAINNAME}' #changed - FS
            traefik.frontend.headers.SSLHost: '${DOMAINNAME}' #changed - FS
            traefik.docker.network: traefik_proxy
            traefik.frontend.passHostHeader: 'true'
            traefik.frontend.headers.SSLForceHost: 'true'
            traefik.frontend.headers.SSLRedirect: 'true'
            traefik.frontend.headers.browserXSSFilter: 'true'
            traefik.frontend.headers.contentTypeNosniff: 'true'
            traefik.frontend.headers.forceSTSHeader: 'true'
            traefik.frontend.headers.STSSeconds: 315360000
            traefik.frontend.headers.STSIncludeSubdomains: 'true'
            traefik.frontend.headers.STSPreload: 'true'
            traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
            traefik.frontend.headers.frameDeny: 'true'
            traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
            # traefik.frontend.auth.forward.address: 'http://oauth:4181'
            # traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
            # traefik.frontend.auth.forward.trustForwardHeader: 'true'
# <any additional parameters>     

    demo1.fabricesemti.com :
        image: linuxserver/nginx                    
        container_name: demo1.fabricesemti.com # update me for new website
        hostname: demo1.fabricesemti.com # update me for new website
        restart: unless-stopped
        networks:
            - traefik_proxy
        ports:
            - '${NGINX_PORT1}:80' # update me for new website
        volumes:
            - '${NGINX_HOME}/demo1.fabricesemti.com/config:/config' # update me for new website
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        labels:
            traefik.enable: 'true'
            traefik.backend: demo1.fabricesemti.com
            traefik.protocol: http
            traefik.port: 80
            traefik.frontend.rule: 'Host:demo1.${DOMAINNAME},www.demo1.${DOMAINNAME}' # update me for new website
            traefik.frontend.headers.SSLHost: 'demo1.${DOMAINNAME}' # update me for new website
            traefik.docker.network: traefik_proxy
            traefik.frontend.passHostHeader: 'true'
            traefik.frontend.headers.SSLForceHost: 'true'
            traefik.frontend.headers.SSLRedirect: 'true'
            traefik.frontend.headers.browserXSSFilter: 'true'
            traefik.frontend.headers.contentTypeNosniff: 'true'
            traefik.frontend.headers.forceSTSHeader: 'true'
            traefik.frontend.headers.STSSeconds: 315360000
            traefik.frontend.headers.STSIncludeSubdomains: 'true'
            traefik.frontend.headers.STSPreload: 'true'
            traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
            traefik.frontend.headers.frameDeny: 'true'
            traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
            # traefik.frontend.auth.forward.address: 'http://oauth:4181'
            # traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
            # traefik.frontend.auth.forward.trustForwardHeader: 'true'
# <any additional parameters>     

    demo2.fabricesemti.com :  # update me for new website
        image: linuxserver/nginx                    
        container_name: demo2.fabricesemti.com # update me for new website
        hostname: demo2.fabricesemti.com # update me for new website
        restart: unless-stopped
        networks:
            - traefik_proxy
        ports:
            - '${NGINX_PORT2}:80' # update me for new website
        volumes:
            - '${NGINX_HOME}/demo2.fabricesemti.com/config:/config' # update me for new website
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        labels:
            traefik.enable: 'true'
            traefik.backend: demo2.fabricesemti.com # update me for new website
            traefik.protocol: http
            traefik.port: 80
            traefik.frontend.rule: 'Host:demo2.${DOMAINNAME},www.demo2.${DOMAINNAME}' # update me for new website
            traefik.frontend.headers.SSLHost: 'demo2.${DOMAINNAME}' # update me for new website
            traefik.docker.network: traefik_proxy
            traefik.frontend.passHostHeader: 'true'
            traefik.frontend.headers.SSLForceHost: 'true'
            traefik.frontend.headers.SSLRedirect: 'true'
            traefik.frontend.headers.browserXSSFilter: 'true'
            traefik.frontend.headers.contentTypeNosniff: 'true'
            traefik.frontend.headers.forceSTSHeader: 'true'
            traefik.frontend.headers.STSSeconds: 315360000
            traefik.frontend.headers.STSIncludeSubdomains: 'true'
            traefik.frontend.headers.STSPreload: 'true'
            traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
            traefik.frontend.headers.frameDeny: 'true'
            traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'