
#------------------ My typical setup -------------------#
version: '2.3'
networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    default:
        ipam:
            driver: default
            config: [{subnet: 192.168.7.0/24}]
services:
#----------------------- Variables ---------------------#
# nginx 
# <service port>                                          # add this to the environment first
# <service's virtual port>                                # this is what the service "thinks" it is uses
# <service config directory>                              # normally within "${USERDIR}/docker/"
# <additional volumes, depending on the service>          # add more places, if needed
# <any additional parameters>    

#----------------------- Template ----------------------#
    nginx :
        image: linuxserver/nginx                    #depends on the name of the image
        container_name: nginx 
        hostname: nginx 
        restart: unless-stopped
        networks:
            - traefik_proxy
        ports:
            - '${NGINX_PORT}:80'
        volumes:
            - '${NGINX_HOME}/config:/config'
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        labels:
            traefik.enable: 'true'
            traefik.backend: nginx 
            traefik.protocol: http
            traefik.port: 80
            traefik.frontend.rule: 'Host:${DOMAINNAME},www.${DOMAINNAME}' #changed - FS
            traefik.frontend.headers.SSLHost: '${DOMAINNAME}' #changed - FS
            traefik.docker.network: traefik_proxy
            traefik.frontend.passHostHeader: 'true'
            traefik.frontend.headers.SSLForceHost: 'true'
            traefik.frontend.headers.SSLRedirect: 'true'
            traefik.frontend.headers.browserXSSFilter: 'true'
            traefik.frontend.headers.contentTypeNosniff: 'true'
            traefik.frontend.headers.forceSTSHeader: 'true'
            traefik.frontend.headers.STSSeconds: 315360000
            traefik.frontend.headers.STSIncludeSubdomains: 'true'
            traefik.frontend.headers.STSPreload: 'true'
            traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
            traefik.frontend.headers.frameDeny: 'true'
            traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
            traefik.frontend.auth.forward.address: 'http://oauth:4181'
            traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
            traefik.frontend.auth.forward.trustForwardHeader: 'true'
# <any additional parameters>            